CREATE TABLE "ST_GROUP" (
"GR_ID" INT UNIQUE,
"GR_NAME" VARCHAR2(255) NOT NULL,
"GR_FAC_ID" INT,
"GR_HEAD_ID" INT);

CREATE sequence "ST_GROUP_GR_ID_SEQ";

CREATE trigger "BI_ST_GROUP_GR_ID"
  before insert on "ST_GROUP"
  for each row
begin
  select "ST_GROUP_GR_ID_SEQ".nextval into :NEW."GR_ID" from dual; end;;/
CREATE TABLE "FACULTYS" (
"FAC_ID" INT UNIQUE NOT NULL,
"FAC_NAME" VARCHAR2(255) NOT NULL,
"FAC_HEAD_NAME" VARCHAR2(255) NOT NULL);

CREATE sequence "FACULTYS_FAC_ID_SEQ";

CREATE trigger "BI_FACULTYS_FAC_ID"
  before insert on "FACULTYS"
  for each row
begin
  select "FACULTYS_FAC_ID_SEQ".nextval into :NEW."FAC_ID" from dual; end;;/
CREATE TABLE "STUDENTS" (
"ST_ID" INT UNIQUE NOT NULL,
"ST_NAME" VARCHAR2(255) NOT NULL,
"ST_GR_ID" INT,
"ST_TEAMMATE_ID" INT);

CREATE sequence "STUDENTS_ST_ID_SEQ";

CREATE trigger "BI_STUDENTS_ST_ID"
  before insert on "STUDENTS"
  for each row
begin
  select "STUDENTS_ST_ID_SEQ".nextval into :NEW."ST_ID" from dual; end;;/
CREATE TABLE "SUBJECTS" (
"SUB_ID" INT UNIQUE NOT NULL,
"SUB_NAME" VARCHAR2(255) NOT NULL,
"SUB_TEACHER_NAME" VARCHAR2(255) NOT NULL);

CREATE sequence "SUBJECTS_SUB_ID_SEQ";

CREATE trigger "BI_SUBJECTS_SUB_ID"
  before insert on "SUBJECTS"
  for each row
begin
  select "SUBJECTS_SUB_ID_SEQ".nextval into :NEW."SUB_ID" from dual; end;;/
CREATE TABLE "MARKS" (
"MARK_ID" INT UNIQUE NOT NULL,
"MARK_ST_ID" INT,
"MARK_SUB_ID" INT,
"MARK_MARK" INT NOT NULL);

CREATE sequence "MARKS_MARK_ID_SEQ";

CREATE trigger "BI_MARKS_MARK_ID"
  before insert on "MARKS"
  for each row
begin
  select "MARKS_MARK_ID_SEQ".nextval into :NEW."MARK_ID" from dual; end;;/
ALTER TABLE "ST_GROUP" ADD CONSTRAINT "ST_GROUP_fk0" FOREIGN KEY ("GR_FAC_ID") REFERENCES "FACULTYS"("FAC_ID");
ALTER TABLE "ST_GROUP" ADD CONSTRAINT "ST_GROUP_fk1" FOREIGN KEY ("GR_HEAD_ID") REFERENCES "STUDENTS"("ST_ID");


ALTER TABLE "STUDENTS" ADD CONSTRAINT "STUDENTS_fk0" FOREIGN KEY ("ST_GR_ID") REFERENCES "ST_GROUP"("GR_ID");


ALTER TABLE "MARKS" ADD CONSTRAINT "MARKS_fk0" FOREIGN KEY ("MARK_ST_ID") REFERENCES "STUDENTS"("ST_ID");
ALTER TABLE "MARKS" ADD CONSTRAINT "MARKS_fk1" FOREIGN KEY ("MARK_SUB_ID") REFERENCES "SUBJECTS"("SUB_ID");

