drop table STUDENT_LIST.FACULTYS CASCADE ;
DROP TABLE STUDENT_LIST.ST_GROUP CASCADE ;
DROP TABLE STUDENT_LIST.STUDENTS CASCADE ;
DROP TABLE STUDENT_LIST.SUBJECTS CASCADE ;
DROP TABLE STUDENT_LIST.MARKS CASCADE ;
commit;

create schema student_list;
grant usage on schema student_list to public;
grant create on schema student_list to public;
commit;

create table student_list.FACULTYS
(
    "FAC_ID"        serial
        unique,
    "FAC_NAME"      varchar(255),
    "FAC_HEAD_NAME" varchar(255)
);
commit;

alter table student_list.FACULTYS
    owner to postgres;
commit;

create table student_list.st_group
(
    "GR_ID"      serial
        unique,
    "GR_NAME"    varchar(255),
    "GR_FAC_ID"  integer
        constraint "GROUP_fk0"
            references student_list.facultys ("FAC_ID"),
    "GR_HEAD_ID" integer
);
commit;

alter table student_list.st_group
    owner to postgres;
commit;

create table student_list.students
(
    "ST_ID"          serial
        unique,
    "ST_NAME"        varchar(255),
    "ST_GR_ID"       integer
        constraint "STUDENTS_fk0"
            references student_list.st_group ("GR_ID"),
    "ST_TEAMMATE_ID" integer
        constraint "STUDENTS_fk1"
            references student_list.students ("ST_ID")
);
commit;

alter table student_list.students
    owner to postgres;
commit;

alter table student_list.st_group
    add constraint "GROUP_fk1"
        foreign key ("GR_HEAD_ID") references student_list.students ("ST_ID");
commit;

create table student_list.subjects
(
    "SUB_ID"           serial
        unique,
    "SUB_NAME"         varchar(255),
    "SUB_TEACHER_NAME" varchar(255)
);
commit;

alter table student_list.subjects
    owner to postgres;
commit;

create table student_list.marks
(
    "MARK_ID"     serial
        unique,
    "MARK_ST_ID"  integer
        constraint "MARKS_fk0"
            references student_list.students ("ST_ID"),
    "MARK_SUB_ID" integer
        constraint "MARKS_fk1"
            references student_list.subjects ("SUB_ID"),
    "MARK_MARK"   integer,
    "MARK_DATE"   varchar(255)
);
commit;

alter table student_list.marks
    owner to postgres;
commit;

INSERT INTO STUDENT_LIST.FACULTYS ("FAC_NAME", "FAC_HEAD_NAME") VALUES ('Faculty1', 'Faculty_Head1');
INSERT INTO STUDENT_LIST.FACULTYS ("FAC_NAME", "FAC_HEAD_NAME") VALUES ('Faculty2', 'Faculty_Head2');
commit;

INSERT INTO STUDENT_LIST.ST_GROUP ("GR_NAME", "GR_FAC_ID") VALUES ('Group1', 1);
INSERT INTO STUDENT_LIST.ST_GROUP ("GR_NAME", "GR_FAC_ID") VALUES ('Group2', 1);
INSERT INTO STUDENT_LIST.ST_GROUP ("GR_NAME", "GR_FAC_ID") VALUES ('Group3', 2);
INSERT INTO STUDENT_LIST.ST_GROUP ("GR_NAME", "GR_FAC_ID") VALUES ('Group4', 2);
commit;
INSERT INTO STUDENT_LIST.STUDENTS ("ST_NAME", "ST_GR_ID") VALUES ('Student1', 1);
INSERT INTO STUDENT_LIST.STUDENTS ("ST_NAME", "ST_GR_ID", "ST_TEAMMATE_ID") VALUES ('Student2', 1, 1);
INSERT INTO STUDENT_LIST.STUDENTS ("ST_NAME", "ST_GR_ID") VALUES ('Student3', 1);
INSERT INTO STUDENT_LIST.STUDENTS ("ST_NAME", "ST_GR_ID") VALUES ('Student4', 1);
commit;
INSERT INTO STUDENT_LIST.STUDENTS ("ST_NAME", "ST_GR_ID") VALUES ('Student5', 2);
INSERT INTO STUDENT_LIST.STUDENTS ("ST_NAME", "ST_GR_ID", "ST_TEAMMATE_ID") VALUES ('Student6', 2, 5);
INSERT INTO STUDENT_LIST.STUDENTS ("ST_NAME", "ST_GR_ID") VALUES ('Student7', 2);
INSERT INTO STUDENT_LIST.STUDENTS ("ST_NAME", "ST_GR_ID") VALUES ('Student8', 2);
commit;
INSERT INTO STUDENT_LIST.STUDENTS ("ST_NAME", "ST_GR_ID") VALUES ('Student9', 3);
INSERT INTO STUDENT_LIST.STUDENTS ("ST_NAME", "ST_GR_ID", "ST_TEAMMATE_ID") VALUES ('Student10', 3, 9);
INSERT INTO STUDENT_LIST.STUDENTS ("ST_NAME", "ST_GR_ID") VALUES ('Student11', 3);
INSERT INTO STUDENT_LIST.STUDENTS ("ST_NAME", "ST_GR_ID") VALUES ('Student12', 3);
commit;
INSERT INTO STUDENT_LIST.STUDENTS ("ST_NAME", "ST_GR_ID") VALUES ('Student13', 4);
INSERT INTO STUDENT_LIST.STUDENTS ("ST_NAME", "ST_GR_ID", "ST_TEAMMATE_ID") VALUES ('Student14', 4, 13);
INSERT INTO STUDENT_LIST.STUDENTS ("ST_NAME", "ST_GR_ID") VALUES ('Student15', 4);
INSERT INTO STUDENT_LIST.STUDENTS ("ST_NAME", "ST_GR_ID") VALUES ('Student16', 4);
commit;
UPDATE STUDENT_LIST.ST_GROUP AS t SET "GR_HEAD_ID" = 4 WHERE t."GR_ID" = 1;
UPDATE STUDENT_LIST.ST_GROUP AS t SET "GR_HEAD_ID" = 8 WHERE t."GR_ID" = 2;
UPDATE STUDENT_LIST.ST_GROUP AS t SET "GR_HEAD_ID" = 12 WHERE t."GR_ID" = 3;
UPDATE STUDENT_LIST.ST_GROUP AS t SET "GR_HEAD_ID" = 16 WHERE t."GR_ID" = 4;
commit;
INSERT INTO STUDENT_LIST.SUBJECTS ("SUB_NAME", "SUB_TEACHER_NAME") VALUES ('Subject1', 'Subject_teacher1');
INSERT INTO STUDENT_LIST.SUBJECTS ("SUB_NAME", "SUB_TEACHER_NAME") VALUES ('Subject2', 'Subject_teacher2');
commit;
INSERT INTO STUDENT_LIST.MARKS ("MARK_ST_ID", "MARK_SUB_ID", "MARK_MARK", "MARK_DATE") VALUES (1, 1, 5, '2022-01-20');
INSERT INTO STUDENT_LIST.MARKS ("MARK_ST_ID", "MARK_SUB_ID", "MARK_MARK", "MARK_DATE") VALUES (1, 1, 4, '2022-01-21');
INSERT INTO STUDENT_LIST.MARKS ("MARK_ST_ID", "MARK_SUB_ID", "MARK_MARK", "MARK_DATE") VALUES (1, 2, 4, '2022-01-20');
INSERT INTO STUDENT_LIST.MARKS ("MARK_ST_ID", "MARK_SUB_ID", "MARK_MARK", "MARK_DATE") VALUES (1, 2, 5, '2022-01-21');
commit;
INSERT INTO STUDENT_LIST.MARKS ("MARK_ST_ID", "MARK_SUB_ID", "MARK_MARK", "MARK_DATE") VALUES (2, 1, 5, '2022-01-20');
INSERT INTO STUDENT_LIST.MARKS ("MARK_ST_ID", "MARK_SUB_ID", "MARK_MARK", "MARK_DATE") VALUES (2, 1, 4, '2022-01-21');
INSERT INTO STUDENT_LIST.MARKS ("MARK_ST_ID", "MARK_SUB_ID", "MARK_MARK", "MARK_DATE") VALUES (2, 2, 4, '2022-01-20');
INSERT INTO STUDENT_LIST.MARKS ("MARK_ST_ID", "MARK_SUB_ID", "MARK_MARK", "MARK_DATE") VALUES (2, 2, 5, '2022-01-21');
commit;
INSERT INTO STUDENT_LIST.MARKS ("MARK_ST_ID", "MARK_SUB_ID", "MARK_MARK", "MARK_DATE") VALUES (3, 1, 5, '2022-01-20');
INSERT INTO STUDENT_LIST.MARKS ("MARK_ST_ID", "MARK_SUB_ID", "MARK_MARK", "MARK_DATE") VALUES (3, 1, 4, '2022-01-21');
INSERT INTO STUDENT_LIST.MARKS ("MARK_ST_ID", "MARK_SUB_ID", "MARK_MARK", "MARK_DATE") VALUES (3, 2, 4, '2022-01-20');
INSERT INTO STUDENT_LIST.MARKS ("MARK_ST_ID", "MARK_SUB_ID", "MARK_MARK", "MARK_DATE") VALUES (3, 2, 5, '2022-01-21');
commit;
INSERT INTO STUDENT_LIST.MARKS ("MARK_ST_ID", "MARK_SUB_ID", "MARK_MARK", "MARK_DATE") VALUES (4, 1, 5, '2022-01-20');
INSERT INTO STUDENT_LIST.MARKS ("MARK_ST_ID", "MARK_SUB_ID", "MARK_MARK", "MARK_DATE") VALUES (4, 1, 4, '2022-01-21');
INSERT INTO STUDENT_LIST.MARKS ("MARK_ST_ID", "MARK_SUB_ID", "MARK_MARK", "MARK_DATE") VALUES (4, 2, 4, '2022-01-20');
INSERT INTO STUDENT_LIST.MARKS ("MARK_ST_ID", "MARK_SUB_ID", "MARK_MARK", "MARK_DATE") VALUES (4, 2, 5, '2022-01-21');
commit;
INSERT INTO STUDENT_LIST.MARKS ("MARK_ST_ID", "MARK_SUB_ID", "MARK_MARK", "MARK_DATE") VALUES (5, 1, 5, '2022-01-20');
INSERT INTO STUDENT_LIST.MARKS ("MARK_ST_ID", "MARK_SUB_ID", "MARK_MARK", "MARK_DATE") VALUES (5, 1, 4, '2022-01-21');
INSERT INTO STUDENT_LIST.MARKS ("MARK_ST_ID", "MARK_SUB_ID", "MARK_MARK", "MARK_DATE") VALUES (5, 2, 4, '2022-01-20');
INSERT INTO STUDENT_LIST.MARKS ("MARK_ST_ID", "MARK_SUB_ID", "MARK_MARK", "MARK_DATE") VALUES (5, 2, 5, '2022-01-21');
commit;
INSERT INTO STUDENT_LIST.MARKS ("MARK_ST_ID", "MARK_SUB_ID", "MARK_MARK", "MARK_DATE") VALUES (6, 1, 5, '2022-01-20');
INSERT INTO STUDENT_LIST.MARKS ("MARK_ST_ID", "MARK_SUB_ID", "MARK_MARK", "MARK_DATE") VALUES (6, 1, 4, '2022-01-21');
INSERT INTO STUDENT_LIST.MARKS ("MARK_ST_ID", "MARK_SUB_ID", "MARK_MARK", "MARK_DATE") VALUES (6, 2, 4, '2022-01-20');
INSERT INTO STUDENT_LIST.MARKS ("MARK_ST_ID", "MARK_SUB_ID", "MARK_MARK", "MARK_DATE") VALUES (6, 2, 5, '2022-01-21');
commit;
INSERT INTO STUDENT_LIST.MARKS ("MARK_ST_ID", "MARK_SUB_ID", "MARK_MARK", "MARK_DATE") VALUES (7, 1, 5, '2022-01-20');
INSERT INTO STUDENT_LIST.MARKS ("MARK_ST_ID", "MARK_SUB_ID", "MARK_MARK", "MARK_DATE") VALUES (7, 1, 4, '2022-01-21');
INSERT INTO STUDENT_LIST.MARKS ("MARK_ST_ID", "MARK_SUB_ID", "MARK_MARK", "MARK_DATE") VALUES (7, 2, 4, '2022-01-20');
INSERT INTO STUDENT_LIST.MARKS ("MARK_ST_ID", "MARK_SUB_ID", "MARK_MARK", "MARK_DATE") VALUES (7, 2, 5, '2022-01-21');
commit;
INSERT INTO STUDENT_LIST.MARKS ("MARK_ST_ID", "MARK_SUB_ID", "MARK_MARK", "MARK_DATE") VALUES (8, 1, 5, '2022-01-20');
INSERT INTO STUDENT_LIST.MARKS ("MARK_ST_ID", "MARK_SUB_ID", "MARK_MARK", "MARK_DATE") VALUES (8, 1, 4, '2022-01-21');
INSERT INTO STUDENT_LIST.MARKS ("MARK_ST_ID", "MARK_SUB_ID", "MARK_MARK", "MARK_DATE") VALUES (8, 2, 4, '2022-01-20');
INSERT INTO STUDENT_LIST.MARKS ("MARK_ST_ID", "MARK_SUB_ID", "MARK_MARK", "MARK_DATE") VALUES (8, 2, 5, '2022-01-21');
commit;
INSERT INTO STUDENT_LIST.MARKS ("MARK_ST_ID", "MARK_SUB_ID", "MARK_MARK", "MARK_DATE") VALUES (9, 1, 5, '2022-01-20');
INSERT INTO STUDENT_LIST.MARKS ("MARK_ST_ID", "MARK_SUB_ID", "MARK_MARK", "MARK_DATE") VALUES (9, 1, 4, '2022-01-21');
INSERT INTO STUDENT_LIST.MARKS ("MARK_ST_ID", "MARK_SUB_ID", "MARK_MARK", "MARK_DATE") VALUES (9, 2, 4, '2022-01-20');
INSERT INTO STUDENT_LIST.MARKS ("MARK_ST_ID", "MARK_SUB_ID", "MARK_MARK", "MARK_DATE") VALUES (9, 2, 5, '2022-01-21');
commit;
INSERT INTO STUDENT_LIST.MARKS ("MARK_ST_ID", "MARK_SUB_ID", "MARK_MARK", "MARK_DATE") VALUES (10, 1, 5, '2022-01-20');
INSERT INTO STUDENT_LIST.MARKS ("MARK_ST_ID", "MARK_SUB_ID", "MARK_MARK", "MARK_DATE") VALUES (10, 1, 4, '2022-01-21');
INSERT INTO STUDENT_LIST.MARKS ("MARK_ST_ID", "MARK_SUB_ID", "MARK_MARK", "MARK_DATE") VALUES (10, 2, 4, '2022-01-20');
INSERT INTO STUDENT_LIST.MARKS ("MARK_ST_ID", "MARK_SUB_ID", "MARK_MARK", "MARK_DATE") VALUES (10, 2, 5, '2022-01-21');
commit;
INSERT INTO STUDENT_LIST.MARKS ("MARK_ST_ID", "MARK_SUB_ID", "MARK_MARK", "MARK_DATE") VALUES (11, 1, 5, '2022-01-20');
INSERT INTO STUDENT_LIST.MARKS ("MARK_ST_ID", "MARK_SUB_ID", "MARK_MARK", "MARK_DATE") VALUES (11, 1, 4, '2022-01-21');
INSERT INTO STUDENT_LIST.MARKS ("MARK_ST_ID", "MARK_SUB_ID", "MARK_MARK", "MARK_DATE") VALUES (11, 2, 4, '2022-01-20');
INSERT INTO STUDENT_LIST.MARKS ("MARK_ST_ID", "MARK_SUB_ID", "MARK_MARK", "MARK_DATE") VALUES (11, 2, 5, '2022-01-21');
commit;
INSERT INTO STUDENT_LIST.MARKS ("MARK_ST_ID", "MARK_SUB_ID", "MARK_MARK", "MARK_DATE") VALUES (12, 1, 5, '2022-01-20');
INSERT INTO STUDENT_LIST.MARKS ("MARK_ST_ID", "MARK_SUB_ID", "MARK_MARK", "MARK_DATE") VALUES (12, 1, 4, '2022-01-21');
INSERT INTO STUDENT_LIST.MARKS ("MARK_ST_ID", "MARK_SUB_ID", "MARK_MARK", "MARK_DATE") VALUES (12, 2, 4, '2022-01-20');
INSERT INTO STUDENT_LIST.MARKS ("MARK_ST_ID", "MARK_SUB_ID", "MARK_MARK", "MARK_DATE") VALUES (12, 2, 5, '2022-01-21');
commit;
INSERT INTO STUDENT_LIST.MARKS ("MARK_ST_ID", "MARK_SUB_ID", "MARK_MARK", "MARK_DATE") VALUES (13, 1, 5, '2022-01-20');
INSERT INTO STUDENT_LIST.MARKS ("MARK_ST_ID", "MARK_SUB_ID", "MARK_MARK", "MARK_DATE") VALUES (13, 1, 4, '2022-01-21');
INSERT INTO STUDENT_LIST.MARKS ("MARK_ST_ID", "MARK_SUB_ID", "MARK_MARK", "MARK_DATE") VALUES (13, 2, 4, '2022-01-20');
INSERT INTO STUDENT_LIST.MARKS ("MARK_ST_ID", "MARK_SUB_ID", "MARK_MARK", "MARK_DATE") VALUES (13, 2, 5, '2022-01-21');
commit;
INSERT INTO STUDENT_LIST.MARKS ("MARK_ST_ID", "MARK_SUB_ID", "MARK_MARK", "MARK_DATE") VALUES (14, 1, 5, '2022-01-20');
INSERT INTO STUDENT_LIST.MARKS ("MARK_ST_ID", "MARK_SUB_ID", "MARK_MARK", "MARK_DATE") VALUES (14, 1, 4, '2022-01-21');
INSERT INTO STUDENT_LIST.MARKS ("MARK_ST_ID", "MARK_SUB_ID", "MARK_MARK", "MARK_DATE") VALUES (14, 2, 4, '2022-01-20');
INSERT INTO STUDENT_LIST.MARKS ("MARK_ST_ID", "MARK_SUB_ID", "MARK_MARK", "MARK_DATE") VALUES (14, 2, 5, '2022-01-21');
commit;
INSERT INTO STUDENT_LIST.MARKS ("MARK_ST_ID", "MARK_SUB_ID", "MARK_MARK", "MARK_DATE") VALUES (15, 1, 5, '2022-01-20');
INSERT INTO STUDENT_LIST.MARKS ("MARK_ST_ID", "MARK_SUB_ID", "MARK_MARK", "MARK_DATE") VALUES (15, 1, 4, '2022-01-21');
INSERT INTO STUDENT_LIST.MARKS ("MARK_ST_ID", "MARK_SUB_ID", "MARK_MARK", "MARK_DATE") VALUES (15, 2, 4, '2022-01-20');
INSERT INTO STUDENT_LIST.MARKS ("MARK_ST_ID", "MARK_SUB_ID", "MARK_MARK", "MARK_DATE") VALUES (15, 2, 5, '2022-01-21');
commit;
INSERT INTO STUDENT_LIST.MARKS ("MARK_ST_ID", "MARK_SUB_ID", "MARK_MARK", "MARK_DATE") VALUES (16, 1, 5, '2022-01-20');
INSERT INTO STUDENT_LIST.MARKS ("MARK_ST_ID", "MARK_SUB_ID", "MARK_MARK", "MARK_DATE") VALUES (16, 1, 4, '2022-01-21');
INSERT INTO STUDENT_LIST.MARKS ("MARK_ST_ID", "MARK_SUB_ID", "MARK_MARK", "MARK_DATE") VALUES (16, 2, 4, '2022-01-20');
INSERT INTO STUDENT_LIST.MARKS ("MARK_ST_ID", "MARK_SUB_ID", "MARK_MARK", "MARK_DATE") VALUES (16, 2, 5, '2022-01-21');

commit ;