DROP TABLE STUDENT_LIST.FACULTYS  CASCADE CONSTRAINTS;
DROP TABLE STUDENT_LIST.ST_GROUP  CASCADE CONSTRAINTS;
DROP TABLE STUDENT_LIST.STUDENTS  CASCADE CONSTRAINTS;
DROP TABLE STUDENT_LIST.SUBJECTS  CASCADE CONSTRAINTS;
DROP TABLE STUDENT_LIST.MARKS  CASCADE CONSTRAINTS;

DROP Sequence FACULTYS_FAC_ID_SEQ;
DROP Sequence ST_GROUP_GR_ID_SEQ;
DROP Sequence STUDENTS_ST_ID_SEQ;
DROP Sequence SUBJECTS_SUB_ID_SEQ;
DROP Sequence MARKS_MARK_ID_SEQ;

CREATE TABLE "FACULTYS" (
                            "FAC_ID" INT UNIQUE ,
                            "FAC_NAME" VARCHAR2(255) ,
                            "FAC_HEAD_NAME" VARCHAR2(255) );

CREATE sequence "FACULTYS_FAC_ID_SEQ";

CREATE trigger "BI_FACULTYS_FAC_ID"
    before insert on "FACULTYS"
    for each row
begin
    select "FACULTYS_FAC_ID_SEQ".nextval into :NEW."FAC_ID" from dual; end;;/

CREATE TABLE "ST_GROUP" (
                            "GR_ID" INT UNIQUE,
                            "GR_NAME" VARCHAR2(255) ,
                            "GR_FAC_ID" INT,
                            "GR_HEAD_ID" INT);

CREATE sequence "ST_GROUP_GR_ID_SEQ";

CREATE trigger "BI_ST_GROUP_GR_ID"
    before insert on "ST_GROUP"
    for each row
begin
    select "ST_GROUP_GR_ID_SEQ".nextval into :NEW."GR_ID" from dual; end;;/

CREATE TABLE "STUDENTS" (
                            "ST_ID" INT UNIQUE ,
                            "ST_NAME" VARCHAR2(255) ,
                            "ST_GR_ID" INT,
                            "ST_TEAMMATE_ID" INT);

CREATE sequence "STUDENTS_ST_ID_SEQ";

CREATE trigger "BI_STUDENTS_ST_ID"
    before insert on "STUDENTS"
    for each row
begin
    select "STUDENTS_ST_ID_SEQ".nextval into :NEW."ST_ID" from dual; end;;/

CREATE TABLE "SUBJECTS" (
                            "SUB_ID" INT UNIQUE ,
                            "SUB_NAME" VARCHAR2(255) ,
                            "SUB_TEACHER_NAME" VARCHAR2(255) );

CREATE sequence "SUBJECTS_SUB_ID_SEQ";

CREATE trigger "BI_SUBJECTS_SUB_ID"
    before insert on "SUBJECTS"
    for each row
begin
    select "SUBJECTS_SUB_ID_SEQ".nextval into :NEW."SUB_ID" from dual; end;;/

CREATE TABLE "MARKS" (
                         "MARK_ID" INT UNIQUE ,
                         "MARK_ST_ID" INT,
                         "MARK_SUB_ID" INT,
                         "MARK_MARK" INT,
                         "MARK_DATE" VARCHAR2(255) );

CREATE sequence "MARKS_MARK_ID_SEQ";

CREATE trigger "BI_MARKS_MARK_ID"
    before insert on "MARKS"
    for each row
begin
    select "MARKS_MARK_ID_SEQ".nextval into :NEW."MARK_ID" from dual; end;;/

ALTER TABLE "ST_GROUP" ADD CONSTRAINT "ST_GROUP_fk0" FOREIGN KEY ("GR_FAC_ID") REFERENCES "FACULTYS"("FAC_ID");
ALTER TABLE "ST_GROUP" ADD CONSTRAINT "ST_GROUP_fk1" FOREIGN KEY ("GR_HEAD_ID") REFERENCES "STUDENTS"("ST_ID");


ALTER TABLE "STUDENTS" ADD CONSTRAINT "STUDENTS_fk0" FOREIGN KEY ("ST_GR_ID") REFERENCES "ST_GROUP"("GR_ID");


ALTER TABLE "MARKS" ADD CONSTRAINT "MARKS_fk0" FOREIGN KEY ("MARK_ST_ID") REFERENCES "STUDENTS"("ST_ID");
ALTER TABLE "MARKS" ADD CONSTRAINT "MARKS_fk1" FOREIGN KEY ("MARK_SUB_ID") REFERENCES "SUBJECTS"("SUB_ID");


INSERT INTO STUDENT_LIST.FACULTYS (FAC_NAME, FAC_HEAD_NAME) VALUES ('Faculty1', 'Faculty_Head1');
INSERT INTO STUDENT_LIST.FACULTYS (FAC_NAME, FAC_HEAD_NAME) VALUES ('Faculty2', 'Faculty_Head2');

INSERT INTO STUDENT_LIST.ST_GROUP (GR_NAME, GR_FAC_ID) VALUES ('Group1', 1);
INSERT INTO STUDENT_LIST.ST_GROUP (GR_NAME, GR_FAC_ID) VALUES ('Group2', 1);
INSERT INTO STUDENT_LIST.ST_GROUP (GR_NAME, GR_FAC_ID) VALUES ('Group3', 2);
INSERT INTO STUDENT_LIST.ST_GROUP (GR_NAME, GR_FAC_ID) VALUES ('Group4', 2);

INSERT INTO STUDENT_LIST.STUDENTS (ST_NAME, ST_GR_ID) VALUES ('Student1', 1);
INSERT INTO STUDENT_LIST.STUDENTS (ST_NAME, ST_GR_ID, ST_TEAMMATE_ID) VALUES ('Student2', 1, 1);
INSERT INTO STUDENT_LIST.STUDENTS (ST_NAME, ST_GR_ID) VALUES ('Student3', 1);
INSERT INTO STUDENT_LIST.STUDENTS (ST_NAME, ST_GR_ID) VALUES ('Student4', 1);

INSERT INTO STUDENT_LIST.STUDENTS (ST_NAME, ST_GR_ID) VALUES ('Student5', 2);
INSERT INTO STUDENT_LIST.STUDENTS (ST_NAME, ST_GR_ID, ST_TEAMMATE_ID) VALUES ('Student6', 2, 5);
INSERT INTO STUDENT_LIST.STUDENTS (ST_NAME, ST_GR_ID) VALUES ('Student7', 2);
INSERT INTO STUDENT_LIST.STUDENTS (ST_NAME, ST_GR_ID) VALUES ('Student8', 2);

INSERT INTO STUDENT_LIST.STUDENTS (ST_NAME, ST_GR_ID) VALUES ('Student9', 3);
INSERT INTO STUDENT_LIST.STUDENTS (ST_NAME, ST_GR_ID, ST_TEAMMATE_ID) VALUES ('Student10', 3, 9);
INSERT INTO STUDENT_LIST.STUDENTS (ST_NAME, ST_GR_ID) VALUES ('Student11', 3);
INSERT INTO STUDENT_LIST.STUDENTS (ST_NAME, ST_GR_ID) VALUES ('Student12', 3);

INSERT INTO STUDENT_LIST.STUDENTS (ST_NAME, ST_GR_ID) VALUES ('Student13', 4);
INSERT INTO STUDENT_LIST.STUDENTS (ST_NAME, ST_GR_ID, ST_TEAMMATE_ID) VALUES ('Student14', 4, 13);
INSERT INTO STUDENT_LIST.STUDENTS (ST_NAME, ST_GR_ID) VALUES ('Student15', 4);
INSERT INTO STUDENT_LIST.STUDENTS (ST_NAME, ST_GR_ID) VALUES ('Student16', 4);

UPDATE STUDENT_LIST.ST_GROUP t SET t.GR_HEAD_ID = 4 WHERE t.GR_ID = 1;
UPDATE STUDENT_LIST.ST_GROUP t SET t.GR_HEAD_ID = 8 WHERE t.GR_ID = 2;
UPDATE STUDENT_LIST.ST_GROUP t SET t.GR_HEAD_ID = 12 WHERE t.GR_ID = 3;
UPDATE STUDENT_LIST.ST_GROUP t SET t.GR_HEAD_ID = 16 WHERE t.GR_ID = 4;

INSERT INTO STUDENT_LIST.SUBJECTS (SUB_NAME, SUB_TEACHER_NAME) VALUES ('Subject1', 'Subject_teacher1');
INSERT INTO STUDENT_LIST.SUBJECTS (SUB_NAME, SUB_TEACHER_NAME) VALUES ('Subject2', 'Subject_teacher2');

INSERT INTO STUDENT_LIST.MARKS (MARK_ST_ID, MARK_SUB_ID, MARK_MARK, MARK_DATE) VALUES (1, 1, 5, '2022-01-20');
INSERT INTO STUDENT_LIST.MARKS (MARK_ST_ID, MARK_SUB_ID, MARK_MARK, MARK_DATE) VALUES (1, 1, 4, '2022-01-21');
INSERT INTO STUDENT_LIST.MARKS (MARK_ST_ID, MARK_SUB_ID, MARK_MARK, MARK_DATE) VALUES (1, 2, 4, '2022-01-20');
INSERT INTO STUDENT_LIST.MARKS (MARK_ST_ID, MARK_SUB_ID, MARK_MARK, MARK_DATE) VALUES (1, 2, 5, '2022-01-21');

INSERT INTO STUDENT_LIST.MARKS (MARK_ST_ID, MARK_SUB_ID, MARK_MARK, MARK_DATE) VALUES (2, 1, 5, '2022-01-20');
INSERT INTO STUDENT_LIST.MARKS (MARK_ST_ID, MARK_SUB_ID, MARK_MARK, MARK_DATE) VALUES (2, 1, 4, '2022-01-21');
INSERT INTO STUDENT_LIST.MARKS (MARK_ST_ID, MARK_SUB_ID, MARK_MARK, MARK_DATE) VALUES (2, 2, 4, '2022-01-20');
INSERT INTO STUDENT_LIST.MARKS (MARK_ST_ID, MARK_SUB_ID, MARK_MARK, MARK_DATE) VALUES (2, 2, 5, '2022-01-21');

INSERT INTO STUDENT_LIST.MARKS (MARK_ST_ID, MARK_SUB_ID, MARK_MARK, MARK_DATE) VALUES (3, 1, 5, '2022-01-20');
INSERT INTO STUDENT_LIST.MARKS (MARK_ST_ID, MARK_SUB_ID, MARK_MARK, MARK_DATE) VALUES (3, 1, 4, '2022-01-21');
INSERT INTO STUDENT_LIST.MARKS (MARK_ST_ID, MARK_SUB_ID, MARK_MARK, MARK_DATE) VALUES (3, 2, 4, '2022-01-20');
INSERT INTO STUDENT_LIST.MARKS (MARK_ST_ID, MARK_SUB_ID, MARK_MARK, MARK_DATE) VALUES (3, 2, 5, '2022-01-21');

INSERT INTO STUDENT_LIST.MARKS (MARK_ST_ID, MARK_SUB_ID, MARK_MARK, MARK_DATE) VALUES (4, 1, 5, '2022-01-20');
INSERT INTO STUDENT_LIST.MARKS (MARK_ST_ID, MARK_SUB_ID, MARK_MARK, MARK_DATE) VALUES (4, 1, 4, '2022-01-21');
INSERT INTO STUDENT_LIST.MARKS (MARK_ST_ID, MARK_SUB_ID, MARK_MARK, MARK_DATE) VALUES (4, 2, 4, '2022-01-20');
INSERT INTO STUDENT_LIST.MARKS (MARK_ST_ID, MARK_SUB_ID, MARK_MARK, MARK_DATE) VALUES (4, 2, 5, '2022-01-21');

INSERT INTO STUDENT_LIST.MARKS (MARK_ST_ID, MARK_SUB_ID, MARK_MARK, MARK_DATE) VALUES (5, 1, 5, '2022-01-20');
INSERT INTO STUDENT_LIST.MARKS (MARK_ST_ID, MARK_SUB_ID, MARK_MARK, MARK_DATE) VALUES (5, 1, 4, '2022-01-21');
INSERT INTO STUDENT_LIST.MARKS (MARK_ST_ID, MARK_SUB_ID, MARK_MARK, MARK_DATE) VALUES (5, 2, 4, '2022-01-20');
INSERT INTO STUDENT_LIST.MARKS (MARK_ST_ID, MARK_SUB_ID, MARK_MARK, MARK_DATE) VALUES (5, 2, 5, '2022-01-21');

INSERT INTO STUDENT_LIST.MARKS (MARK_ST_ID, MARK_SUB_ID, MARK_MARK, MARK_DATE) VALUES (6, 1, 5, '2022-01-20');
INSERT INTO STUDENT_LIST.MARKS (MARK_ST_ID, MARK_SUB_ID, MARK_MARK, MARK_DATE) VALUES (6, 1, 4, '2022-01-21');
INSERT INTO STUDENT_LIST.MARKS (MARK_ST_ID, MARK_SUB_ID, MARK_MARK, MARK_DATE) VALUES (6, 2, 4, '2022-01-20');
INSERT INTO STUDENT_LIST.MARKS (MARK_ST_ID, MARK_SUB_ID, MARK_MARK, MARK_DATE) VALUES (6, 2, 5, '2022-01-21');

INSERT INTO STUDENT_LIST.MARKS (MARK_ST_ID, MARK_SUB_ID, MARK_MARK, MARK_DATE) VALUES (7, 1, 5, '2022-01-20');
INSERT INTO STUDENT_LIST.MARKS (MARK_ST_ID, MARK_SUB_ID, MARK_MARK, MARK_DATE) VALUES (7, 1, 4, '2022-01-21');
INSERT INTO STUDENT_LIST.MARKS (MARK_ST_ID, MARK_SUB_ID, MARK_MARK, MARK_DATE) VALUES (7, 2, 4, '2022-01-20');
INSERT INTO STUDENT_LIST.MARKS (MARK_ST_ID, MARK_SUB_ID, MARK_MARK, MARK_DATE) VALUES (7, 2, 5, '2022-01-21');

INSERT INTO STUDENT_LIST.MARKS (MARK_ST_ID, MARK_SUB_ID, MARK_MARK, MARK_DATE) VALUES (8, 1, 5, '2022-01-20');
INSERT INTO STUDENT_LIST.MARKS (MARK_ST_ID, MARK_SUB_ID, MARK_MARK, MARK_DATE) VALUES (8, 1, 4, '2022-01-21');
INSERT INTO STUDENT_LIST.MARKS (MARK_ST_ID, MARK_SUB_ID, MARK_MARK, MARK_DATE) VALUES (8, 2, 4, '2022-01-20');
INSERT INTO STUDENT_LIST.MARKS (MARK_ST_ID, MARK_SUB_ID, MARK_MARK, MARK_DATE) VALUES (8, 2, 5, '2022-01-21');

INSERT INTO STUDENT_LIST.MARKS (MARK_ST_ID, MARK_SUB_ID, MARK_MARK, MARK_DATE) VALUES (9, 1, 5, '2022-01-20');
INSERT INTO STUDENT_LIST.MARKS (MARK_ST_ID, MARK_SUB_ID, MARK_MARK, MARK_DATE) VALUES (9, 1, 4, '2022-01-21');
INSERT INTO STUDENT_LIST.MARKS (MARK_ST_ID, MARK_SUB_ID, MARK_MARK, MARK_DATE) VALUES (9, 2, 4, '2022-01-20');
INSERT INTO STUDENT_LIST.MARKS (MARK_ST_ID, MARK_SUB_ID, MARK_MARK, MARK_DATE) VALUES (9, 2, 5, '2022-01-21');

INSERT INTO STUDENT_LIST.MARKS (MARK_ST_ID, MARK_SUB_ID, MARK_MARK, MARK_DATE) VALUES (10, 1, 5, '2022-01-20');
INSERT INTO STUDENT_LIST.MARKS (MARK_ST_ID, MARK_SUB_ID, MARK_MARK, MARK_DATE) VALUES (10, 1, 4, '2022-01-21');
INSERT INTO STUDENT_LIST.MARKS (MARK_ST_ID, MARK_SUB_ID, MARK_MARK, MARK_DATE) VALUES (10, 2, 4, '2022-01-20');
INSERT INTO STUDENT_LIST.MARKS (MARK_ST_ID, MARK_SUB_ID, MARK_MARK, MARK_DATE) VALUES (10, 2, 5, '2022-01-21');

INSERT INTO STUDENT_LIST.MARKS (MARK_ST_ID, MARK_SUB_ID, MARK_MARK, MARK_DATE) VALUES (11, 1, 5, '2022-01-20');
INSERT INTO STUDENT_LIST.MARKS (MARK_ST_ID, MARK_SUB_ID, MARK_MARK, MARK_DATE) VALUES (11, 1, 4, '2022-01-21');
INSERT INTO STUDENT_LIST.MARKS (MARK_ST_ID, MARK_SUB_ID, MARK_MARK, MARK_DATE) VALUES (11, 2, 4, '2022-01-20');
INSERT INTO STUDENT_LIST.MARKS (MARK_ST_ID, MARK_SUB_ID, MARK_MARK, MARK_DATE) VALUES (11, 2, 5, '2022-01-21');

INSERT INTO STUDENT_LIST.MARKS (MARK_ST_ID, MARK_SUB_ID, MARK_MARK, MARK_DATE) VALUES (12, 1, 5, '2022-01-20');
INSERT INTO STUDENT_LIST.MARKS (MARK_ST_ID, MARK_SUB_ID, MARK_MARK, MARK_DATE) VALUES (12, 1, 4, '2022-01-21');
INSERT INTO STUDENT_LIST.MARKS (MARK_ST_ID, MARK_SUB_ID, MARK_MARK, MARK_DATE) VALUES (12, 2, 4, '2022-01-20');
INSERT INTO STUDENT_LIST.MARKS (MARK_ST_ID, MARK_SUB_ID, MARK_MARK, MARK_DATE) VALUES (12, 2, 5, '2022-01-21');

INSERT INTO STUDENT_LIST.MARKS (MARK_ST_ID, MARK_SUB_ID, MARK_MARK, MARK_DATE) VALUES (13, 1, 5, '2022-01-20');
INSERT INTO STUDENT_LIST.MARKS (MARK_ST_ID, MARK_SUB_ID, MARK_MARK, MARK_DATE) VALUES (13, 1, 4, '2022-01-21');
INSERT INTO STUDENT_LIST.MARKS (MARK_ST_ID, MARK_SUB_ID, MARK_MARK, MARK_DATE) VALUES (13, 2, 4, '2022-01-20');
INSERT INTO STUDENT_LIST.MARKS (MARK_ST_ID, MARK_SUB_ID, MARK_MARK, MARK_DATE) VALUES (13, 2, 5, '2022-01-21');

INSERT INTO STUDENT_LIST.MARKS (MARK_ST_ID, MARK_SUB_ID, MARK_MARK, MARK_DATE) VALUES (14, 1, 5, '2022-01-20');
INSERT INTO STUDENT_LIST.MARKS (MARK_ST_ID, MARK_SUB_ID, MARK_MARK, MARK_DATE) VALUES (14, 1, 4, '2022-01-21');
INSERT INTO STUDENT_LIST.MARKS (MARK_ST_ID, MARK_SUB_ID, MARK_MARK, MARK_DATE) VALUES (14, 2, 4, '2022-01-20');
INSERT INTO STUDENT_LIST.MARKS (MARK_ST_ID, MARK_SUB_ID, MARK_MARK, MARK_DATE) VALUES (14, 2, 5, '2022-01-21');

INSERT INTO STUDENT_LIST.MARKS (MARK_ST_ID, MARK_SUB_ID, MARK_MARK, MARK_DATE) VALUES (15, 1, 5, '2022-01-20');
INSERT INTO STUDENT_LIST.MARKS (MARK_ST_ID, MARK_SUB_ID, MARK_MARK, MARK_DATE) VALUES (15, 1, 4, '2022-01-21');
INSERT INTO STUDENT_LIST.MARKS (MARK_ST_ID, MARK_SUB_ID, MARK_MARK, MARK_DATE) VALUES (15, 2, 4, '2022-01-20');
INSERT INTO STUDENT_LIST.MARKS (MARK_ST_ID, MARK_SUB_ID, MARK_MARK, MARK_DATE) VALUES (15, 2, 5, '2022-01-21');

INSERT INTO STUDENT_LIST.MARKS (MARK_ST_ID, MARK_SUB_ID, MARK_MARK, MARK_DATE) VALUES (16, 1, 5, '2022-01-20');
INSERT INTO STUDENT_LIST.MARKS (MARK_ST_ID, MARK_SUB_ID, MARK_MARK, MARK_DATE) VALUES (16, 1, 4, '2022-01-21');
INSERT INTO STUDENT_LIST.MARKS (MARK_ST_ID, MARK_SUB_ID, MARK_MARK, MARK_DATE) VALUES (16, 2, 4, '2022-01-20');
INSERT INTO STUDENT_LIST.MARKS (MARK_ST_ID, MARK_SUB_ID, MARK_MARK, MARK_DATE) VALUES (16, 2, 5, '2022-01-21');